# Site Metadata
site_name: artart222 Portfolio/Blog
site_description: Portfolio and blog.
base_url: https://artart.dev
author: Artin Mobasher

asset_dirs:
  - ./source/assets

# Output Paths
source_directory: ./source
data_dir: ./source/data
output_directory: ./output

template_dirs:
  - "./templates/blog-theme/"

# Template Engine
template_engine: django # or jinja2, etc.

templates_by_type:
  blog: post.html
  page: post.html
  index: post.html

collections:
  blog:
    path: ./source/blogs
    type: blog
    template: post.html
    url_prefix: blog
    index:
      enabled: true
      template: blog-indexer.html
      output_path: blog-indexer/index.html
      title: Blog
  pages:
    path: ./source
    type: page
    template: post.html

frontend:
  theme: blog-theme
  assets:
    css:
      - /styles/tailwind.css
      - /styles/code.css
    js: []
  tailwind:
    enabled: true
    input: ./styles/tailwind.input.css
    output: ./styles/tailwind.css
    config: ./tailwind.config.js
    minify: false
  export_data:
    enabled: false
    output_dir: ./output/data

plugins:
  - CollectionIndexerPlugin
  - SpecialPagesPlugin
  - PageKeyWordExtractor
  - SitemapPlugin

# Program log levels:
# Debug = 10
# Info = 20
# Warning = 30
# Error = 40
# Critical = 50
log_level: 10

# Navigation (can also be in a separate data file)
navigation:
  - title: Home
    type: index
  - title: Blog
    type: blog-index
