# Generated by Django 5.2.1 on 2026-04-30 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runtime", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("old_available_quantity", models.IntegerField(default=0)),
                ("new_available_quantity", models.IntegerField(default=0)),
                ("delta_available_quantity", models.IntegerField(default=0)),
                ("old_reserved_quantity", models.IntegerField(default=0)),
                ("new_reserved_quantity", models.IntegerField(default=0)),
                ("delta_reserved_quantity", models.IntegerField(default=0)),
                ("actor", models.CharField(blank=True, max_length=192)),
                ("reason", models.CharField(blank=True, max_length=280)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="runtime.inventoryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="media_file",
            field=models.FileField(blank=True, upload_to="runtime-media/"),
        ),
    ]
