# Generated by Codex for phase 5 integration foundation.

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runtime", "0002_inventory_adjustment_and_media_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_payment", "Pending Payment"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("fulfilled", "Fulfilled"),
                    ("refunded", "Refunded"),
                    ("partially_refunded", "Partially Refunded"),
                ],
                default="draft",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="event_idempotency_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=160),
        ),
        migrations.CreateModel(
            name="IntegrationOutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=120)),
                ("provider_domain", models.CharField(blank=True, max_length=64)),
                ("provider_name", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("dead_letter", "Dead Letter"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, default="", max_length=160),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="integrationoutboxevent",
            index=models.Index(
                fields=["status", "next_attempt_at"],
                name="runtime_inte_status_21a195_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationoutboxevent",
            index=models.Index(
                fields=["provider_domain", "status"],
                name="runtime_inte_provide_9df784_idx",
            ),
        ),
    ]
