# Generated by Django 5.2.1 on 2026-05-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0003_phase5_integrations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='integrationoutboxevent',
            new_name='runtime_int_status_1cce68_idx',
            old_name='runtime_inte_status_21a195_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationoutboxevent',
            new_name='runtime_int_provide_5e50f5_idx',
            old_name='runtime_inte_provide_9df784_idx',
        ),
    ]
